package com.dynamicpay.opp.sdk.model;

/**
 * Payment link creation response.
 */
public class PaymentResponse {

    /** Order number generated by the DynamicPay platform. */
    private String orderNum;

    /** Short-lived access credential for the payment page. */
    private String accessKey;

    /**
     * Complete payment page URL, including orderNum, accessKey and all redirect parameters.
     * Redirect the user directly to this URL: window.location.href = payUrl
     */
    private String payUrl;

    public PaymentResponse(String orderNum, String accessKey, String payUrl) {
        this.orderNum = orderNum;
        this.accessKey = accessKey;
        this.payUrl = payUrl;
    }

    public String getOrderNum() { return orderNum; }
    public String getAccessKey() { return accessKey; }
    public String getPayUrl() { return payUrl; }
}
